name: 빌드

on: [push, pull_request]

jobs:
  build_wheels:
    name: ${{ matrix.os }}에서 Wheel 빌드하기
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      
      - name: cibuildwheel 설치
        run: python -m pip install cibuildwheel==1.12.0

      - name: Wheel 빌드
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl